baseURL = "https://juliengrv.github.io/"
languageCode = "en-us"
title = "Darkin"
theme = "poison"

[params]
brand = "Darkin"
remote_brand_image = "https://github.com/JulienGrv.png"
dark_mode = false
front_page_content = ["posts"]
menu = [
    { Name = "About", URL = "/about/", HasChildren = false },
    { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
]
email_url = "mailto:julien.grave@proton.me"
github_url = "https://github.com/JulienGrv"
linkedin_url = "https://www.linkedin.com/in/julien-grave/"
rss_icon = true
rss_section = "posts"
